---
name: "hadolint"
description: "hadolint by Pipeline Components"
author: "Robbert Müller <spam.me@grols.ch>"
branding:
  icon: "flag"
  color: "green"
inputs:
  dockerfile:
    description: "Dockerfile to lint"
    required: false
    default: "Dockerfile"
  options:
    description: "Additional options"
    required: false
    default: ""
runs:
  using: "docker"
  image: docker://pipelinecomponents/hadolint
  args:
    - hadolint
    - "${{ inputs.options }}"
    - "${{ inputs.dockerfile }}"
